services:

  pgadmin:
    container_name: 5142026_pgadmin_container
    image: dpage/pgadmin4:9.3
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      TZ: Europe/Moscow
    volumes:
       - 5142026_pgadmin:/var/lib/pgadmin
    ports:
      - "127.0.0.1:${PGADMIN_PORT:-5040}:80"
    networks:
      - 5142026_network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  5142026_pgadmin:

networks:
  5142026_network:
    driver: bridge
